"""empty message

Revision ID: 442c11dcf42d
Revises: 6d1fb09e267a
Create Date: 2022-06-10 10:58:16.985568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '442c11dcf42d'
down_revision = '6d1fb09e267a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    # ### end Alembic commands ###
